#entrada de dados
nome = input("imforme seu nome:")
cpf = input("imforme seu cpf:")
telefone = input("imforme seu telefone:")
email = input("imforme seu email:")
endereco = input("imforme seu endereco:")
genero = input("imforme seu genero:")
escolaridade = input("imforme seu escolaride:")
signo = input("imforme seu signo:")
tipo_sanguineo = input("imforme seu tipo sanguineo:")

#saida de dados
print(f"nome:{nome}.")
print(f"cpf:{cpf}.")
print(f"telefone:{telefone}.")
print(f"email:{email}.")
print(f"endereco:{endereco}.")
print(f"genero:{genero}.")
print(f"escolaridade:{escolaridade}.")
print(f"signo:{signo}.")
print(f"tipo sanguinio:{tipo sanguineo}.")